### ISSUE TITLE
files are missing 

### ISSUE THREAD

**Issue by Sandeepgsn** [aws/aws-swf-flow-library#10]
There are so many class are missing but thats being used in project. I am wondering if its getting compile. 
list of missing files
CronWorkflowClientFactory
CronWorkflowSelfClient

**Comment by Jianchu** [comment]
This is because you didn't enable your annotation processor, those class are automatically generated through annotation processor. Please refer https://docs.aws.amazon.com/amazonswf/latest/awsflowguide/setup.html for the details.
